<?php
use Sb\View\Components\MailboxWidget;
use Sb\View\Components\Ad;
?>
<div id="content-center">
    <div class="mailbox-message">
        <form action="" method="post" >            
            <div class="mm-header">
                <div class="inner-padding">
                    <div class="mmh-from">
                        <span class="mmh-label"><?php _e("De", "s1b"); ?></span>
                        <?php echo $this->message->getRecipient()->getUserName(); ?>                                
                    </div>
                    <div class="mmh-date">
                        <span class="mmh-label"><?php _e("A", "s1b"); ?></span>
                        <?php echo $this->message->getSender()->getUserName(); ?>
                        <input type="hidden" name="Addressee" readonly="readonly" value="<?php echo $this->message->getSender()->getUserName(); ?>"/>
                    </div>
                    <div class="mmh-subject">
                        <span class="mmh-label"><?php _e("Sujet", "s1b"); ?></span>
                        <?php echo 'RE: ' . $this->message->getTitle(); ?>
                        <input type="hidden" name="Title" readonly="readonly" value="<?php echo 'RE: ' . $this->message->getTitle(); ?>"/>
                    </div>
                </div>
            </div>                     
            <div class="mm-body">
                <div class="mmb-title"><?php _e("Message","s1b");?></div>
                <textarea class="input-item mm-inputbody" name="Message" ><?php if (isset($_POST['Message'])) echo $_POST['Message']; ?></textarea>
            </div>                
            <div class="buttons-bar">
                <div class="inner-padding">
                    <button class="button bt-black-m float-right margin-left"><?php _e("Envoyer","s1b");?></button>
                    <a class="button bt-blue-xs float-right" href="javascript:history.back()" class="link"><?php _e("Annuler", "s1b") ?></a>
                </div>
            </div>
        </form>            
    </div>
</div>
<div id="content-right">    
    <div class="right-frame">
        <?php
        $mailboxWidget = new MailboxWidget();
        echo $mailboxWidget->get();
        ?>
    </div>
    <div class="right-frame">
        <?php
        $ad = new Ad("","");
        echo $ad->get();
        ?>
    </div>
</div>