<div id="content-top">    
    <div class="carousel-wrap">
        <ul class="carousel-items">
            <li>
                <div class="accroche accroche-1">
                    <div class="ci-content">
                        <div class="ci-text"><span class="ci-maintext">Trouvez&nbsp;</span></br>le livre qui fera plaisir à votre ami dans sa liste d'envies</div>
                        <div class="ci-button"><a class="bt-carroussel button" href="<?php echo $this->subscribeLink; ?>">S'inscrire</a></div>
                    </div>
                </div>
            </li>
            <li>
                <div class="accroche accroche-2">
                    <div class="ci-content">
                        <div class="ci-text"><span class="ci-maintext">Découvrez&nbsp;</span></br>Les derniers coups de coeur de vos amis</div>
                        <div class="ci-button"><a class="bt-carroussel button" href="<?php echo $this->subscribeLink; ?>">S'inscrire</a></div>
                    </div>
                </div>

            </li>
            <li>
                <div class="accroche accroche-3">
                    <div class="ci-content">
                        <div class="ci-text"><span class="ci-maintext">Gérez&nbsp;</span></br>votre bibliothèque avec la fonction de prêt et emprunt et conservez une trace de vos livres préférés</div>
                        <div class="ci-button"><a class="bt-carroussel button" href="<?php echo $this->subscribeLink; ?>">S'inscrire</a></div>
                    </div>
                </div>
            </li>
        </ul>
    </div>
</div>
<div id="content-center">
    <div class="pushed-chronicle">
        <?php echo $this->chronicle; ?>
    </div>
    <div class="pushed-books pushedBooks">        
        <div class="pb-content">
            <?php echo $this->boh; ?>
        </div>
    </div>
</div>
<div id="content-right">
    <div class="right-frame">
        <a title="<?php echo $this->autoPromoWishListTitle; ?>" href="<?php echo $this->autoPromoWishListLink; ?>"><img border='0' src="<?php echo $this->autoPromoWishListImage; ?>" alt="<?php echo $this->autoPromoWishListTitle; ?>"/></a>
    </div>
    <div class="right-frame">
        <?php echo $this->ad; ?>
    </div>
    <div class="right-frame">
        <?php echo $this->twitter; ?>
    </div>
    <div class="right-frame">
        <?php echo $this->faceBookFrame; ?>
    </div>

    <!--    <div class="right-frame">
            <div class="pinterest-frame">
                <div class="pf-title">Cher bouquin sur Pinterest</div>
                <div class="pf-content">
                    bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla 
                    <br/>
                    bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla 
                    <br/>
                    bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla 
                    <br/>
                    bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla 
                    <br/>
                </div>
            </div>
        </div>-->
</div>
