<div id="content-wide">
    <div class="annexe-page">
        <div class="ap-left">
            <div class="inner-padding-10">
                <div class="ap-title">Comment aider Cherbouquin ?</div>
                <div class="tm-description" style="font-size:1.3em">
                    Vous souhaitez acheter sur Internet dans l’une des boutiques de cette liste, cliquez sur le lien ou la bannière correspondante puis faites vos achats normalement.<br/>
                    Comme vous pouvez l’imaginer, nous ne sommes pas contre un coup de pouce... <br/>Merci pour votre aide
                </div>  

                <div class="tm-description" style="font-size:1.3em;margin-top:15px;"><strong>Les catégories</strong></div>
                <div class="tm-librarylink" style="font-size:1.2em"><a href="#Achats_groupes" class="link">Achats groupés</a></div>
                <div class="tm-librarylink" style="font-size:1.2em"><a href="#Billeterie_spectacles" class="link">Billeterie et spectacles</a></div>
                <div class="tm-librarylink" style="font-size:1.2em"><a href="#Cadeaux" class="link">Cadeaux</a></div>
                <div class="tm-librarylink" style="font-size:1.2em"><a href="#Divers" class="link">Divers</a></div>
                <div class="tm-librarylink" style="font-size:1.2em"><a href="#Jeu" class="link">Jeux et jouets</a></div>
                <div class="tm-librarylink" style="font-size:1.2em"><a href="#Culture" class="link">Livres, musique, biens culturels</a></div>
                <div class="tm-librarylink" style="font-size:1.2em"><a href="#Interieur" class="link">Maison et intérieur</a></div>
                <div class="tm-librarylink" style="font-size:1.2em"><a href="#Sites_généralistes" class="link">Sites généralistes</a></div>
                <div class="tm-librarylink" style="font-size:1.2em"><a href="#Shopping" class="link">Shopping</a></div>
                <div class="tm-librarylink" style="font-size:1.2em"><a href="#Restaurants" class="link">Restaurants</a></div>
                <div class="tm-librarylink" style="font-size:1.2em"><a href="#Telecom" class="link">Télécom et services</a></div>
                <div class="tm-librarylink" style="font-size:1.2em"><a href="#Voyage" class="link">Voyages</a></div>

            </div>
        </div>
        <div class="ap-right">
            <div class="inner-padding-10">
                <div class="ap-line team-member">
                    <div class="tm-resume">

                        <div class="tm-name" style="margin-top:20px" id="Restaurants">Restaurants <a href="#" class="link" style="font-size:0.6em;">(retour en haut)</a></div>
                        <div class="tm-description" style="font-size:1.2em">
                            <table style="margin-bottom:10px">
                                <tr>
                                    <td style="width:120px">
                                        <a href="http://ad.zanox.com/ppc/?23462806C989860464T" class="link" target="_blank"><?php _e("La Fourchette", "s1b"); ?></a>
                                    </td>
                                    <td>
                                        <a href="http://ad.zanox.com/ppc/?23462806C989860464T" target="_blank"><img src="http://ad.zanox.com/ppv/?23462806C989860464" align="bottom" width="468" height="60" border="0" hspace="1" alt="LaFourchette - Image Banner 468 x 60"></a>
                                    </td>
                                </tr>
                            </table>
                        </div>

                        <div style="background:url(http://www.cherbouquin.fr/wp-content/plugins/share1Book/Resources/images/horizontal-sep-1.png) no-repeat scroll 0 0 transparent;float: left;height: 23px;width: 100%;margin-top:5px" ></div>

                        <div class="tm-name" style="margin-top:20px" id="Cadeaux">Cadeaux <a href="#" class="link" style="font-size:0.6em;">(retour en haut)</a></div>
                        <div class="tm-description" style="font-size:1.2em">
                            <table style="margin-bottom:10px">
                                <tr>
                                    <td style="width:120px">
                                        <a href="http://ad.zanox.com/ppc/?23659079C1749978152T" class="link" target="_blank"><?php _e("aquarelle Gourmand", "s1b"); ?></a>
                                    </td>
                                    <td>
                                        <a href="http://ad.zanox.com/ppc/?23659079C1749978152T"><img src="http://ad.zanox.com/ppv/?23659079C1749978152" align="bottom" border="0" hspace="1" alt="Boutique de chocolats en ligne. Livraison partout en France"></a>
                                    </td>
                                </tr>
                            </table>
                            <table style="margin-bottom:10px">
                                <tr>
                                    <td style="width:120px">
                                        <a href="http://ad.zanox.com/ppc/?23333141C18599138T" class="link" target="_blank"><?php _e("Blurb", "s1b"); ?></a>
                                    </td>
                                    <td>
                                        <a href="http://ad.zanox.com/ppc/?23333141C18599138T"><img src="http://ad.zanox.com/ppv/?24407680C1814719139" align="bottom" width="468" height="60" border="0" hspace="1" alt="Blurb"></a>
                                    </td>
                                </tr>
                            </table>
                            <table style="margin-bottom:10px">
                                <tr>
                                    <td style="width:120px">
                                        <a href="http://ad.zanox.com/ppc/?23462855C493766106T" class="link" target="_blank"><?php _e("Coolcadeau", "s1b"); ?></a>
                                    </td>
                                    <td>
                                        <a href="http://ad.zanox.com/ppc/?23462855C493766106T" target="_blank"><img src="http://ad.zanox.com/ppv/?23462855C493766106" align="bottom" width="468" height="60" border="0" hspace="1" alt="Bannière Coffret cadeau 468x60.gif"></a>
                                    </td>
                                </tr>
                            </table>
                            <table style="margin-bottom:10px">
                                <tr>
                                    <td style="width:120px">
                                        <a href="http://ad.zanox.com/ppc/?23478067C1198799362T" class="link" target="_blank"><?php _e("Foto.com", "s1b"); ?></a>
                                    </td>
                                    <td>
                                        <a href="http://ad.zanox.com/ppc/?23478067C1198799362T" target="_blank"><img src="http://ad.zanox.com/ppv/?23478067C1198799362" align="bottom" width="468" height="60" border="0" hspace="1" alt="Foto.com"></a>
                                    </td>
                                </tr>
                            </table>
                            <table style="margin-bottom:10px">
                                <tr>
                                    <td style="width:120px">
                                        <a href="http://ad.zanox.com/ppc/?23462867C1159447975T" class="link" target="_blank"><?php _e("Mydays", "s1b"); ?></a>
                                    </td>
                                    <td>
                                        <a href="http://ad.zanox.com/ppc/?23462867C1159447975T" target="_blank"><img src="http://ad.zanox.com/ppv/?23462867C1159447975" align="bottom" width="468" height="60" border="0" hspace="1" alt="Des cadeaux originaux pour les mordus d´aventure"></a>
                                    </td>
                                </tr>
                            </table>
                        </div>

                        <div style="background:url(http://www.cherbouquin.fr/wp-content/plugins/share1Book/Resources/images/horizontal-sep-1.png) no-repeat scroll 0 0 transparent;float: left;height: 23px;width: 100%;margin-top:5px" ></div>

                        <div class="tm-name" style="margin-top:20px" id="Culture">Livres, musique, biens culturels <a href="#" class="link" style="font-size:0.6em;">(retour en haut)</a></div>
                        <div class="tm-description" style="font-size:1.2em">
                            <table style="margin-bottom:10px">
                                <tr>
                                    <td style="width:120px">
                                        <a href="http://ad.zanox.com/ppc/?23488907C1752767759T" class="link" target="_blank"><?php _e("Abebooks", "s1b"); ?></a>
                                    </td>
                                    <td>
                                        <a href="http://ad.zanox.com/ppc/?23488907C1752767759T" target="_blank"><img src="http://ad.zanox.com/ppv/?23488907C1752767759" align="bottom" width="468" height="60" border="0" hspace="1" alt="AbeBooks.fr - Passionnés de livres"></a>
                                    </td>
                                </tr>
                            </table>
                            <table style="margin-bottom:10px">
                                <tr>
                                    <td style="width:120px">
                                        <a href="https://www.amazon.fr/b?node=301061&tag=cherbouqui-21&camp=1534&creative=5294&linkCode=ur1&adid=12VFBS1HQ92C5JYVDKYE&" class="link" target="_blank"><?php _e("Amazon", "s1b"); ?></a>
                                    </td>
                                    <td>
                                        <iframe src="http://rcm-fr.amazon.fr/e/cm?t=cherbouqui-21&o=8&p=26&l=ur1&category=books&banner=19G44GCK4TAC6YE1BX02&f=ifr" width="468" height="60" scrolling="no" border="0" marginwidth="0" style="border:none;" frameborder="0"></iframe>
                                    </td>
                                </tr>
                            </table>
                            <table style="margin-bottom:10px">
                                <tr>
                                    <td style="width:120px">
                                        <a href="http://ad.zanox.com/ppc/?23488931C415843845T" class="link" target="_blank"><?php _e("Fnac", "s1b"); ?></a>
                                    </td>
                                    <td>
                                        <a href="http://ad.zanox.com/ppc/?23488931C415843845T" target="_blank"><img src="http://ad.zanox.com/ppv/?23488931C415843845" align="bottom" width="468" height="60" border="0" hspace="1" alt="Actualité-Musique-468x60"></a>
                                    </td>
                                </tr>
                            </table>
                            <table style="margin-bottom:10px">
                                <tr>
                                    <td style="width:120px">
                                        <a href="http://ad.zanox.com/ppc/?23515079C1159179498T" class="link" target="_blank"><?php _e("France Loisirs", "s1b"); ?></a>
                                    </td>
                                    <td>
                                        <a href="http://ad.zanox.com/ppc/?23515079C1159179498T" target="_blank"><img src="http://ad.zanox.com/ppv/?23515079C1159179498" align="bottom" width="468" height="60" border="0" hspace="1" alt="468x60_marque"></a>
                                    </td>
                                </tr>
                            </table>
                        </div>

                        <div style="background:url(http://www.cherbouquin.fr/wp-content/plugins/share1Book/Resources/images/horizontal-sep-1.png) no-repeat scroll 0 0 transparent;float: left;height: 23px;width: 100%;margin-top:5px" ></div>

                        <div class="tm-name" style="margin-top:20px" id="Billeterie_spectacles">Billeterie et spectacles <a href="#" class="link" style="font-size:0.6em;">(retour en haut)</a></div>
                        <div class="tm-description" style="font-size:1.2em">
                            <table style="margin-bottom:10px">
                                <tr>
                                    <td style="width:120px">
                                        <a href="http://ad.zanox.com/ppc/?23473593C497754840T" class="link" target="_blank"><?php _e("Fnac", "s1b"); ?></a>
                                    </td>
                                    <td>
                                        <a href="http://ad.zanox.com/ppc/?23473593C497754840T" target="_blank"><img src="http://ad.zanox.com/ppv/?23473593C497754840" align="bottom" width="468" height="60" border="0" hspace="1" alt="FNAC_generiq.gif"></a>
                                    </td>
                                </tr>
                            </table>
                        </div>
                        <div class="tm-description" style="font-size:1.2em">
                            <table style="margin-bottom:10px">
                                <tr>
                                    <td style="width:120px">
                                        <a href="http://ad.zanox.com/ppc/?23473605C1289646372T" class="link" target="_blank"><?php _e("France Billet", "s1b"); ?></a>
                                    </td>
                                    <td>
                                        <a href="http://ad.zanox.com/ppc/?23473605C1289646372T" target="_blank"><img src="http://ad.zanox.com/ppv/?23473605C1289646372" align="bottom" width="468" height="60" border="0" hspace="1" alt="partRFB_gene2.gif"></a>
                                    </td>
                                </tr>
                            </table>
                        </div>

                        <div style="background:url(http://www.cherbouquin.fr/wp-content/plugins/share1Book/Resources/images/horizontal-sep-1.png) no-repeat scroll 0 0 transparent;float: left;height: 23px;width: 100%;margin-top:5px" ></div>

                        <div class="tm-name" style="margin-top:20px" id="Jeu">Jeux et jouets <a href="#" class="link" style="font-size:0.6em;">(retour en haut)</a></div>
                        <div class="tm-description" style="font-size:1.2em">
                            <table style="margin-bottom:10px">
                                <tr>
                                    <td style="width:120px">
                                        <a href="http://ad.zanox.com/ppc/?23482145C4146358T" class="link" target="_blank"><?php _e("MyToys", "s1b"); ?></a>
                                    </td>
                                    <td>
                                        <a href="http://ad.zanox.com/ppc/?23482145C4146358T" target="_blank"><img src="http://ad.zanox.com/ppv/?23482145C4146358" align="bottom" width="468" height="60" border="0" hspace="1" alt="05 Loisirs créatifs"></a>
                                    </td>
                                </tr>
                            </table>
                            <table style="margin-bottom:10px">
                                <tr>
                                    <td style="width:120px">
                                        <a href="http://ad.zanox.com/ppc/?23494901C219852084T" class="link" target="_blank"><?php _e("Toys R us", "s1b"); ?></a>
                                    </td>
                                    <td>
                                        <a href="http://ad.zanox.com/ppc/?23494901C219852084T" target="_blank"><img src="http://ad.zanox.com/ppv/?23494901C219852084" align="bottom" width="468" height="60" border="0" hspace="1" alt="BRU_468x60.gif"></a>
                                    </td>
                                </tr>
                            </table>
                        </div>

                        <div style="background:url(http://www.cherbouquin.fr/wp-content/plugins/share1Book/Resources/images/horizontal-sep-1.png) no-repeat scroll 0 0 transparent;float: left;height: 23px;width: 100%;margin-top:5px" ></div>

                        <div class="tm-name" style="margin-top:20px" id="Sites_généralistes">Sites généralistes <a href="#" class="link" style="font-size:0.6em;">(retour en haut)</a></div>
                        <div class="tm-description" style="font-size:1.2em">
                            <table style="margin-bottom:10px">
                                <tr>
                                    <td style="width:120px">
                                        <a href="http://www.amazon.fr/gp/product/B007HCCOD0?ie=UTF8&tag=cherbouqui-21&linkCode=xm2&camp=1642&creativeASIN=B007HCCOD0" class="link" target="_blank"><?php _e("Amazon", "s1b"); ?></a>
                                    </td>
                                    <td>
                                        <iframe src="http://rcm-fr.amazon.fr/e/cm?t=cherbouqui-21&o=8&p=26&l=ur1&category=electronics&banner=1EHKJJ5FT55Y7YD9G0G2&f=ifr" width="468" height="60" scrolling="no" border="0" marginwidth="0" style="border:none;" frameborder="0"></iframe>
                                    </td>
                                </tr>
                            </table>
                            <table style="margin-bottom:10px">
                                <tr>
                                    <td style="width:120px">
                                        <a href="http://ad.zanox.com/ppc/?23462764C1835418404T" class="link" target="_blank"><?php _e("Boulanger", "s1b"); ?></a>
                                    </td>
                                    <td>
                                        <a href="http://ad.zanox.com/ppc/?23462764C1835418404T" target="_blank"><img src="http://ad.zanox.com/ppv/?23462764C1835418404" align="bottom" width="468" height="60" border="0" hspace="1" alt="468x60_aff1"></a>
                                    </td>
                                </tr>
                            </table>
                            <table style="margin-bottom:10px">
                                <tr>
                                    <td style="width:120px">
                                        <a href="http://ad.zanox.com/ppc/?23462753C1568904929T" class="link" target="_blank"><?php _e("Fnac", "s1b"); ?></a>
                                    </td>
                                    <td>
                                        <a href="http://ad.zanox.com/ppc/?23462753C1568904929T" target="_blank"><img src="http://ad.zanox.com/ppv/?23462753C1568904929" align="bottom" width="468" height="60" border="0" hspace="1" alt="Apple-iMac-iPad-MacBook-468x60"></a>
                                    </td>
                                </tr>
                            </table>
                            <table style="margin-bottom:10px">
                                <tr>
                                    <td style="width:120px">
                                        <a href="http://ad.zanox.com/ppc/?23478039C1756535825T" class="link" target="_blank"><?php _e("Pixmania", "s1b"); ?></a>
                                    </td>
                                    <td>
                                        <a href="http://ad.zanox.com/ppc/?23478039C1756535825T" target="_blank"><img src="http://ad.zanox.com/ppv/?23478039C1756535825" align="bottom" width="468" height="60" border="0" hspace="1" alt="Découvrez notre nouvel univers Loveshop !"></a>
                                    </td>
                                </tr>
                            </table>
                            <table style="margin-bottom:10px">
                                <tr>
                                    <td style="width:120px">
                                        <a href="http://ad.zanox.com/ppc/?23462761C2141660145T" class="link" target="_blank"><?php _e("Price Minister", "s1b"); ?></a>
                                    </td>
                                    <td>
                                        <a href="http://ad.zanox.com/ppc/?23462761C2141660145T" target="_blank"><img src="http://ad.zanox.com/ppv/?23462761C2141660145" align="bottom" width="468" height="60" border="0" hspace="1" alt=". 3.0 Générique 468x60"></a>
                                    </td>
                                </tr>
                            </table>
                            <table style="margin-bottom:10px">
                                <tr>
                                    <td style="width:120px">
                                        <a href="http://ad.zanox.com/ppc/?23473635C1298448337T" class="link" target="_blank"><?php _e("Rue du commerce", "s1b"); ?></a>
                                    </td>
                                    <td>
                                        <a href="http://ad.zanox.com/ppc/?23473635C1298448337T" target="_blank"><img src="http://ad.zanox.com/ppv/?23473635C1298448337" align="bottom" width="468" height="60" border="0" hspace="1" alt="super promos_468x60"></a>
                                    </td>
                                </tr>
                            </table>
                        </div>

                        <div style="background:url(http://www.cherbouquin.fr/wp-content/plugins/share1Book/Resources/images/horizontal-sep-1.png) no-repeat scroll 0 0 transparent;float: left;height: 23px;width: 100%;margin-top:5px" ></div>

                        <div class="tm-name" style="margin-top:20px" id="Shopping">Shopping <a href="#" class="link" style="font-size:0.6em;">(retour en haut)</a></div>
                        <div class="tm-description" style="font-size:1.2em">
                            <table style="margin-bottom:10px">
                                <tr>
                                    <td style="width:120px">
                                        <a href="http://ad.zanox.com/ppc/?23464701C503089253T" class="link" target="_blank"><?php _e("Cyrillus", "s1b"); ?></a>
                                    </td>
                                    <td>
                                        <a href="http://ad.zanox.com/ppc/?23464701C503089253T" target="_blank"><img src="http://ad.zanox.com/ppv/?23464701C503089253" align="bottom" width="468" height="60" border="0" hspace="1" alt="mode femme, homme, enfant et linge de maison"></a>
                                    </td>
                                </tr>
                            </table>
                            <table style="margin-bottom:10px">
                                <tr>
                                    <td style="width:120px">
                                        <a href="http://ad.zanox.com/ppc/?23624622C1901477456T" class="link" target="_blank"><?php _e("Etam", "s1b"); ?></a>
                                    </td>
                                    <td>
                                        <a href="http://ad.zanox.com/ppc/?23624622C1901477456T"><img src="http://ad.zanox.com/ppv/?23624622C1901477456" align="bottom" width="468" height="60" border="0" hspace="1" alt="Bannières générales - 468x60"></a>
                                    </td>
                                </tr>
                            </table>
                            <table style="margin-bottom:10px">
                                <tr>
                                    <td style="width:120px">
                                        <a href="http://ad.zanox.com/ppc/?23674607C1827395546T" class="link" target="_blank"><?php _e("La Redoute.fr", "s1b"); ?></a>
                                    </td>
                                    <td>
                                        <a href="http://ad.zanox.com/ppc/?23674607C1827395546T"><img src="http://ad.zanox.com/ppv/?23674607C1827395546" align="bottom" width="468" height="60" border="0" hspace="1" alt="1. Evenement 1 - 468x60"></a>
                                    </td>
                                </tr>
                            </table>
                            <table style="margin-bottom:10px">
                                <tr>
                                    <td style="width:120px">
                                        <a href="http://ad.zanox.com/ppc/?23901978C772615977T" class="link" target="_blank"><?php _e("Monoprix", "s1b"); ?></a>
                                    </td>
                                    <td>
                                        <a href="http://ad.zanox.com/ppc/?23901978C772615977T"><img src="http://ad.zanox.com/ppv/?23901978C772615977" align="bottom" width="468" height="60" border="0" hspace="1" alt="Mode - 468x60"></a>
                                    </td>
                                </tr>
                            </table>
                            <table style="margin-bottom:10px">
                                <tr>
                                    <td style="width:120px">
                                        <a href="http://ad.zanox.com/ppc/?23473661C479879608T" class="link" target="_blank"><?php _e("Pimkie", "s1b"); ?></a>
                                    </td>
                                    <td>
                                        <a href="http://ad.zanox.com/ppc/?23473661C479879608T" target="_blank"><img src="http://ad.zanox.com/ppv/?23473661C479879608" align="bottom" border="0" hspace="1" alt="logo"></a>
                                    </td>
                                </tr>
                            </table>
                            <table style="margin-bottom:10px">
                                <tr>
                                    <td style="width:120px">
                                        <a href="http://ad.zanox.com/ppc/?23462839C390637577T" class="link" target="_blank"><?php _e("Sarenza", "s1b"); ?></a>
                                    </td>
                                    <td>
                                        <a href="http://ad.zanox.com/ppc/?23462839C390637577T" target="_blank"><img src="http://ad.zanox.com/ppv/?23462839C390637577" align="bottom" width="468" height="60" border="0" hspace="1" alt="1.1  468x60 - 1"></a>
                                    </td>
                                </tr>
                            </table>
                            <table style="margin-bottom:10px">
                                <tr>
                                    <td style="width:120px">
                                        <a href="http://ad.zanox.com/ppc/?23478023C945767446T" class="link" target="_blank"><?php _e("Tommy Hilfiger", "s1b"); ?></a>
                                    </td>
                                    <td>
                                        <a href="http://ad.zanox.com/ppc/?23478023C945767446T" target="_blank"><img src="http://ad.zanox.com/ppv/?23478023C945767446" align="bottom" width="468" height="60" border="0" hspace="1" alt="Banner 468x60 la promotion"></a>
                                    </td>
                                </tr>
                            </table>
                            <table style="margin-bottom:10px">
                                <tr>
                                    <td style="width:120px">
                                        <a href="http://ad.zanox.com/ppc/?23624658C619455816T" class="link" target="_blank"><?php _e("Urban Outfitters", "s1b"); ?></a>
                                    </td>
                                    <td>
                                        <a href="http://ad.zanox.com/ppc/?23624658C619455816T"><img src="http://ad.zanox.com/ppv/?23624658C619455816" align="bottom" width="468" height="60" border="0" hspace="1" alt="Nouvelles Promotions - 468x60"></a>
                                    </td>
                                </tr>
                            </table>
							<table style="margin-bottom:10px">
                                <tr>
                                    <td style="width:120px">
                                        <a href="http://ad.zanox.com/ppc/?23725151C2106910171T" class="link" target="_blank"><?php _e("Yoox", "s1b"); ?></a>
                                    </td>
                                    <td>
                                        <a href="http://ad.zanox.com/ppc/?23725151C2106910171T"><img src="http://ad.zanox.com/ppv/?23725151C2106910171" align="bottom" border="0" hspace="1" alt="Toutes les plus grandes marques de mode et de design sont sur YOOX"></a>
                                    </td>
                                </tr>
                            </table>
                        </div>

                        <div style="background:url(http://www.cherbouquin.fr/wp-content/plugins/share1Book/Resources/images/horizontal-sep-1.png) no-repeat scroll 0 0 transparent;float: left;height: 23px;width: 100%;margin-top:5px" ></div>

                        <div class="tm-name" style="margin-top:20px" id="Interieur">Maison et intérieur <a href="#" class="link" style="font-size:0.6em;">(retour en haut)</a></div>
                        <div class="tm-description" style="font-size:1.2em">
                            <table style="margin-bottom:10px">
                                <tr>
                                    <td style="width:120px">
                                        <a href="http://ad.zanox.com/ppc/?23901985C1855311497T" class="link" target="_blank"><?php _e("Castorama", "s1b"); ?></a>
                                    </td>
                                    <td>
                                        <a href="http://ad.zanox.com/ppc/?23901985C1855311497T"><img src="http://ad.zanox.com/ppv/?23901985C1855311497" align="bottom" width="468" height="60" border="0" hspace="1" alt="468x60.gif"></a>
                                    </td>
                                </tr>
                            </table>
                            <table style="margin-bottom:10px">
                                <tr>
                                    <td style="width:120px">
                                        <a href="http://ad.zanox.com/ppc/?23462719C184769758T" class="link" target="_blank"><?php _e("Conforama", "s1b"); ?></a>
                                    </td>
                                    <td>
                                        <a href="http://ad.zanox.com/ppc/?23462719C184769758T" target="_blank"><img src="http://ad.zanox.com/ppv/?23462719C184769758" align="bottom" width="468" height="60" border="0" hspace="1" alt="confo1_468_60"></a>
                                    </td>
                                </tr>
                            </table>
                            <table style="margin-bottom:10px">
                                <tr>
                                    <td style="width:120px">
                                        <a href="http://ad.zanox.com/ppc/?23572198C1007516642T" class="link" target="_blank"><?php _e("Françoise Saget", "s1b"); ?></a>
                                    </td>
                                    <td>
                                        <a href="http://ad.zanox.com/ppc/?23572198C1007516642T" target="_blank"><img src="http://ad.zanox.com/ppv/?23572198C1007516642" align="bottom" width="468" height="60" border="0" hspace="1" alt="Générique 468x60_2"></a>
                                    </td>
                                </tr>
                            </table>
                            <table style="margin-bottom:10px">
                                <tr>
                                    <td style="width:120px">
                                        <a href="http://ad.zanox.com/ppc/?23624643C449511000T" class="link" target="_blank"><?php _e("Vente-unique.com", "s1b"); ?></a>
                                    </td>
                                    <td>
                                        <a href="http://ad.zanox.com/ppc/?23624643C449511000T"><img src="http://ad.zanox.com/ppv/?23624643C449511000" align="bottom" width="468" height="60" border="0" hspace="1" alt="Best seller 2011 V2 468x60"></a>
                                    </td>
                                </tr>
                            </table>
                        </div>

                        <div style="background:url(http://www.cherbouquin.fr/wp-content/plugins/share1Book/Resources/images/horizontal-sep-1.png) no-repeat scroll 0 0 transparent;float: left;height: 23px;width: 100%;margin-top:5px" ></div>

                        <div class="tm-name" style="margin-top:20px" id="Voyage">Voyages <a href="#" class="link" style="font-size:0.6em;">(retour en haut)</a></div>
                        <div class="tm-description" style="font-size:1.2em">
                            <table style="margin-bottom:10px">
                                <tr>
                                    <td style="width:120px">
                                        <a href="http://ad.zanox.com/ppc/?23659074C544512063T" class="link" target="_blank"><?php _e("Alpinresorts.com", "s1b"); ?></a>
                                    </td>
                                    <td>
                                        <a href="http://ad.zanox.com/ppc/?23659074C544512063T"><img src="http://ad.zanox.com/ppv/?23659074C544512063" align="bottom" width="468" height="60" border="0" hspace="1" alt="Alpin Resorts 468 x 60"></a>
                                    </td>
                                </tr>
                            </table>
                            <table style="margin-bottom:10px">
                                <tr>
                                    <td style="width:120px">
                                        <a href="http://ad.zanox.com/ppc/?23488893C1445959429T" class="link" target="_blank"><?php _e("Europcar", "s1b"); ?></a>
                                    </td>
                                    <td>
                                        <a href="http://ad.zanox.com/ppc/?23488893C1445959429T" target="_blank"><img src="http://ad.zanox.com/ppv/?23488893C1445959429" align="bottom" width="468" height="60" border="0" hspace="1" alt="Banniere 468 x 60"></a>
                                    </td>
                                </tr>
                            </table>
                            <table style="margin-bottom:10px">
                                <tr>
                                    <td style="width:120px">
                                        <a href="http://ad.zanox.com/ppc/?23515063C1740929211T" class="link" target="_blank"><?php _e("Lastminute.com", "s1b"); ?></a>
                                    </td>
                                    <td>
                                        <a href="http://ad.zanox.com/ppc/?23515063C1740929211T" target="_blank"><img src="http://ad.zanox.com/ppv/?23515063C1740929211" align="bottom" width="468" height="60" border="0" hspace="1" alt="DP- Image Banner 468 x 60"></a>
                                    </td>
                                </tr>
                            </table>
                            <table style="margin-bottom:10px">
                                <tr>
                                    <td style="width:120px">
                                        <a href="http://ad.zanox.com/ppc/?23572209C1468420694T" class="link" target="_blank"><?php _e("National Citer", "s1b"); ?></a>
                                    </td>
                                    <td>
                                        <a href="http://ad.zanox.com/ppc/?23572209C1468420694T" target="_blank"><img src="http://ad.zanox.com/ppv/?23572209C1468420694" align="bottom" width="468" height="60" border="0" hspace="1" alt="468x60_affaire.gif"></a>
                                    </td>
                                </tr>
                            </table>
                            <table style="margin-bottom:10px">
                                <tr>
                                    <td style="width:120px">
                                        <a href="http://ad.zanox.com/ppc/?23659066C1452845558T" class="link" target="_blank"><?php _e("Voyagesauchan.com", "s1b"); ?></a>
                                    </td>
                                    <td>
                                        <a href="http://ad.zanox.com/ppc/?23659066C1452845558T"><img src="http://ad.zanox.com/ppv/?23659066C1452845558" align="bottom" width="468" height="60" border="0" hspace="1" alt="generique_468x60_sejour.gif"></a>
                                    </td>
                                </tr>
                            </table>
                        </div>

                        <div style="background:url(http://www.cherbouquin.fr/wp-content/plugins/share1Book/Resources/images/horizontal-sep-1.png) no-repeat scroll 0 0 transparent;float: left;height: 23px;width: 100%;margin-top:5px" ></div>

                        <div class="tm-name" style="margin-top:20px" id="Achats_groupes">Achats groupés <a href="#" class="link" style="font-size:0.6em;">(retour en haut)</a></div>
                        <div class="tm-description" style="font-size:1.2em">
                            <table style="margin-bottom:10px">
                                <tr>
                                    <td style="width:120px">
                                        <a href="http://ad.zanox.com/ppc/?23462691C330615949T" class="link" target="_blank"><?php _e("Groupon", "s1b"); ?></a>
                                    </td>
                                    <td>
                                        <a href="http://ad.zanox.com/ppc/?23462691C330615949T" target="_blank"><img src="http://ad.zanox.com/ppv/?23462691C330615949" align="bottom" width="468" height="60" border="0" hspace="1" alt="Bannières Génériques 2012 468x60"></a>
                                    </td>
                                </tr>
                            </table>
                        </div> 

                        <div style="background:url(http://www.cherbouquin.fr/wp-content/plugins/share1Book/Resources/images/horizontal-sep-1.png) no-repeat scroll 0 0 transparent;float: left;height: 23px;width: 100%;margin-top:5px" ></div>

                        <div class="tm-name" style="margin-top:20px" id="Telecom">Télécom et services <a href="#" class="link" style="font-size:0.6em;">(retour en haut)</a></div>
                        <div class="tm-description" style="font-size:1.2em">
                            <table style="margin-bottom:10px">
                                <tr>
                                    <td style="width:120px">
                                        <a href="http://ad.zanox.com/ppc/?23462801C1582375050T" class="link" target="_blank"><?php _e("Numéricable", "s1b"); ?></a>
                                    </td>
                                    <td>
                                        <a href="http://ad.zanox.com/ppc/?23462801C1582375050T" target="_blank"><img src="http://ad.zanox.com/ppv/?23462801C1582375050" align="bottom" width="468" height="60" border="0" hspace="1" alt="11.TV Premium-468x60-GIF"></a>
                                    </td>
                                </tr>
                            </table>
                            <table style="margin-bottom:10px">
                                <tr>
                                    <td style="width:120px">
                                        <a href="http://ad.zanox.com/ppc/?23462713C1036879992T" class="link" target="_blank"><?php _e("Orange", "s1b"); ?></a>
                                    </td>
                                    <td>
                                        <a href="http://ad.zanox.com/ppc/?23462713C1036879992T" target="_blank"><img src="http://ad.zanox.com/ppv/?23462713C1036879992" align="bottom" width="468" height="60" border="0" hspace="1" alt="10.11 Campagne 6 : Offre Open 468x60"></a>
                                    </td>
                                </tr>
                            </table>
                            <table style="margin-bottom:10px">
                                <tr>
                                    <td style="width:120px">
                                        <a href="http://ad.zanox.com/ppc/?23515056C987259394T" class="link" target="_blank"><?php _e("Virgin Mobile", "s1b"); ?></a>
                                    </td>
                                    <td>
                                        <a href="http://ad.zanox.com/ppc/?23515056C987259394T" target="_blank"><img src="http://ad.zanox.com/ppv/?23515056C987259394" align="bottom" width="468" height="60" border="0" hspace="1" alt="VM_Clic to call_468x60.gif"></a>
                                    </td>
                                </tr>
                            </table>
                        </div>

                        <div style="background:url(http://www.cherbouquin.fr/wp-content/plugins/share1Book/Resources/images/horizontal-sep-1.png) no-repeat scroll 0 0 transparent;float: left;height: 23px;width: 100%;margin-top:5px" ></div>

                        <div class="tm-name" style="margin-top:20px" id="Divers">Divers <a href="#" class="link" style="font-size:0.6em;">(retour en haut)</a></div>
                        <div class="tm-description" style="font-size:1.2em">
                            <table style="margin-bottom:10px">
                                <tr>
                                    <td style="width:120px">
                                        <a href="http://ad.zanox.com/ppc/?23572190C1398407890T" class="link" target="_blank"><?php _e("FDJ", "s1b"); ?></a>
                                    </td>
                                    <td>
                                        <a href="http://ad.zanox.com/ppc/?23572190C1398407890T" target="_blank"><img src="http://ad.zanox.com/ppv/?23572190C1398407890" align="bottom" border="0" hspace="1" alt="0. FDJ - Logo"></a>
                                    </td>
                                </tr>
                            </table>
                            <table style="margin-bottom:10px">
                                <tr>
                                    <td style="width:120px">
                                        <a href="http://ad.zanox.com/ppc/?23901999C1213900943T" class="link" target="_blank"><?php _e("Florajet", "s1b"); ?></a>
                                    </td>
                                    <td>
                                        <a href="http://ad.zanox.com/ppc/?23901999C1213900943T"><img src="http://ad.zanox.com/ppv/?23901999C1213900943" align="bottom" width="468" height="60" border="0" hspace="1" alt="Générique 468x60"></a>
                                    </td>
                                </tr>
                            </table>
                            <table style="margin-bottom:10px">
                                <tr>
                                    <td style="width:120px">
                                        <a href="http://ad.zanox.com/ppc/?23478079C29682904T" class="link" target="_blank"><?php _e("Zooplus", "s1b"); ?></a>
                                    </td>
                                    <td>
                                        <a href="http://ad.zanox.com/ppc/?23478079C29682904T" target="_blank"><img src="http://ad.zanox.com/ppv/?23478079C29682904" align="bottom" width="468" height="60" border="0" hspace="1" alt="www.zooplus.fr - Mon Animalerie en Ligne"></a>
                                    </td>
                                </tr>
                            </table>
                        </div>


                    </div>
                </div>
            </div>
        </div>
    </div>        
</div>