<div class="annexe-page">
    <div class="ap-left">
        <div class="inner-padding-10">
            <div class="ap-title"><?php _e("Nos partenaires", "s1b"); ?></div>
            <div class="tm-description" style="font-size:1.2em">
                Nous remercions tous nos partenaires qui nous permettent de vous proposer un contenu enrichi.
                <br/><br/>Si vous souhaitez devenir partenaire, n'hésitez pas à nous contacter:
                <br/><strong>Olivier Rebiffé</strong> 
                <br/>téléphone: 06-89-77-27-06
                <br/>email : olivier@cherbouquin.fr
                <br/><br/>
            </div>
        </div>        
    </div>
    <div class="ap-right">
        <div class="inner-padding-10">

            <div class="ap-line team-member">
                <div class="tm-resume">
                    <div class="tm-description" style="font-size:1.2em">
                        <!-- // new table \\ -->
                        <table style="margin-bottom:10px;height:100px">
                            <tr>
                                <td style="width:120px">
                                    <a href="http://www.lesdedicaces.com/" title="lesdedicaces.com" target="_blank">
                                        <img class="image-frame" style="display:block;float:left;width:75%;height:75%;" src="http://www.cherbouquin.fr/images/partenaires/lesdedicaces.jpg" alt="lesdedicaces.com">
                                    </a>
                                </td>
                                <td style="width:450px">
                                    <strong><a href="http://www.lesdedicaces.com/" class="link" target="_blank">lesdedicaces.com</a>, le moteur de recherche des séances de dédicaces</strong>
                                    <br/>  Francophone et gratuit, lesdedicaces.com permet de rechercher et d'annoncer facilement des séances de dédicaces. Littérature, BD, photographie, peinture, sport, danse, théâtre, musique… toutes les rencontres-dédicaces sont sur lesdedicaces.com ! 
                                </td>
                            </tr>
                        </table>
                        
                        <!-- // new table \\ -->                        
                        <table style="margin-bottom:10px">
                            <tr>
                                <td style="width:120px">
                                    <a href="http://www.ligneclaire.info/" title="Ligne Claire, La BD lue par Jean-Laurent Truc" target="_blank">
                                        <img class="image-frame" style="display:block;float:left;width:75%;height:75%;" src="http://www.cherbouquin.fr/images/partenaires/Ligne-Claire-logo.jpg" alt="Logo Ligne Claire">
                                    </a>
                                </td>
                                <td style="width:450px">
                                    <strong><a href="http://www.ligneclaire.info/" class="link" target="_blank">Ligne Claire</a>, La BD lue par Jean-Laurent Truc</strong>
                                    <br/>Journaliste  je traite l’actualité BD, sorties, rencontres, économie. Conjuguer passion pour le 9e Art et activité professionnelle a été et reste une chance que je vous ferai partager avec mon site. Au menu mes rencontres et mes coups de cœur sur fond de ligne claire.
                                </td>
                            </tr>
                        </table>

                        



                    </div>
                </div>
            </div>

        </div>
    </div>        
</div>