<div id="chronicle-form">
<?php _e("Votre chronique a été créée correctement", "s1b"); ?>
<br />
<?php _e("Vous pouvez la consultez en cliquant sur le lien suivant : ","s1b");?>
<a href="<?php echo $this->chronicleLink;?>" target="_blank" class="link"><?php _e("Voir la chronique","s1b")?></a> <br />
<a href="<?php echo $this->postOnFacebookLink;?>" target="_blank" class="link"><?php _e("Poster sur facebook","s1b")?></a> <br />
</div>