<div id="chronicle-form">
    <h1>
    <?php if ($this->form->getChronicleId()) {?>
        <?php echo sprintf("Vous allez éditer une chronique pour le groupe \"%s\".", $this->group->getName());?>
    <?php } else { ?>
        <?php echo sprintf("Vous allez créer une chronique pour le groupe \"%s\".", $this->group->getName());?>
    <?php }?>
    </h1>
    <a class="help" href="<?php echo $this->helpUrl; ?>" target="_blank">(Aide sur le formulaire)</a>
    <?php echo $this->form?>
</div>
