<div id="chronicle-form">
    <h1>
    <?php if ($this->form->getChronicleId()) {?>
        <?php echo sprintf("Vous allez éditer une chronique pour le groupe \"%s\".", $this->group->getName());?>
    <?php } else { ?>
        <?php echo sprintf("Vous allez créer une chronique pour le groupe \"%s\".", $this->group->getName());?>
    <?php }?>
    </h1>
    <?php echo $this->form?>    
</div>
