<?php
use Sb\Helpers\ArrayHelper;
?>
<div id="content-wide">
    <div class="annexe-page">
        <div class="ap-left">
            <div class="inner-padding-10">
                <div class="ap-title"><?php _e("Contact","s1b");?></div>
                <div class="ap-description"><?php _e("Remplissez le formulaire et nous vous répondrons dans les meilleurs délais","s1b");?></div>
            </div>        
        </div>
        <div class="ap-right">
            <div class="inner-padding-10">
                <form action="" method="post">
                    <div class="ap-line">
                        <div class="ap-label"><?php echo __("Nom *", "s1b"); ?></div>
                        <input type="text" class="textinput input-item" name="contactName" id="contactName" value="<?php echo ArrayHelper::getSafeFromArray($_POST, "contactName", ""); ?>" class="requiredField" />
                    </div>
                    <div class="ap-line">
                        <div class="ap-label"><?php echo __("Prénom *", "s1b"); ?></div>
                        <input type="text" class="textinput input-item" name="contactFirstName" id="contactFirstName" value="<?php echo ArrayHelper::getSafeFromArray($_POST, "contactFirstName", ""); ?>" class="requiredField" />
                    </div>
                    <div class="ap-line">
                        <div class="ap-label"><?php echo __("Email *", "s1b"); ?></div>
                        <input type="text" class="textinput input-item" name="email" id="email" value="<?php echo ArrayHelper::getSafeFromArray($_POST, "email", ""); ?>" class="requiredField" />
                    </div>
                    <div class="ap-line">
                        <div class="ap-label"><?php echo __("Message *", "s1b"); ?></div>
                        <textarea class="input-item" name="comments" id="commentsText"><?php echo ArrayHelper::getSafeFromArray($_POST, "comments", ""); ?></textarea>                    
                    </div>
                    <div class="buttons-bar">
                        <div class="inner-padding">
                            <?php _e("*champs obligatoires", "s1b"); ?>                                
                            <input type="checkbox" name="sendCopy" id="sendCopy" value="true"<?php if (ArrayHelper::getSafeFromArray($_POST, "sendCopy", false)) echo ' checked="checked"'; ?> />
                            <?php echo __("Recevoir une copie du message", "s1b"); ?>
                            <button class="float-right button bt-black-m margin-right margin-left"><?php _e("Valider","s1b");?></button>
                            <?php if (!$_POST) {?>
                            <a class="button bt-blue-xs float-right" href="javascript:history.back()" class="link"><?php _e("Annuler", "s1b") ?></a>
                            <?php } ?>
                        </div>
                    </div>
                </form>
            </div>
        </div>        
    </div>
</div>