<?php

use Sb\View\PushedBook,
    Sb\Helpers\HTTPHelper,
    Sb\Entity\Urls,
    Sb\View\Components\Ad;

?>
<div id="content-center">
    <div class="recommand">
        <?php if (!$this->userBook) { ?>
            <div class="recommand-error">
                <?php
                echo __("Vous ne possédez pas ce livre", "s1b") . '<br/><a href=' . $this->bookLink . '>' . __("Ajouter", "s1b") . " "
                    . $this->book->getTitle() . " " . __("à votre bibliothèque", "s1b") . '</a>'; ?>
            </div>
        <?php } else { ?>
            <form action="<?php echo HTTPHelper::link(Urls::USER_MAILBOX_SUBMIT_RECOMMAND)?>" method="post">

                <input type="hidden" name="id" value="<?php echo $this->book->getId(); ?>">
                <input type="hidden" name="IdAddressee" value="<?php echo $this->friendIdList; ?>">
                <input type="hidden" name="title"  value="<?php echo $this->user->getFirstName() . " " . __("vous recommande: ", "s1b") . $this->book->getTitle() . " " . __("de", "s1b")
                           . " " . $this->book->getOrderableContributors(); ?>">

                <div class="mailbox-new-message">
                    <div class="mnm-title"><?php _e("Partager ce livre", "s1b"); ?></div>
                    <?php
                    $bookView = new PushedBook($this->book, false);
                    echo $bookView->get();
                    ?>
                    <div class="mnm-line">
                        <span class="mnm-label"><?php _e("A", "s1b"); ?></span>
                        <?php
                        if (count($this->friendList) == 0) {
                            ?>
                            <a class="link"
                               href="<?php echo HTTPHelper::Link(Urls::USER_FRIENDS_SELECTION); ?>"><?php _e("sélectionner le(s) destinataires(s)", "s1b"); ?></a>
                        <?php } else { ?>
                            <a class="link"
                               href="<?php echo HTTPHelper::Link(Urls::USER_FRIENDS_SELECTION); ?>"><?php _e("modifier le(s) destinataires(s)", "s1b"); ?></a>
                            <br/>

                            <?php
                            foreach ($this->friendList as $friend) {
                                echo $friend->getUserName() . ";";
                            }
                        } ?>
                    </div>
                    <div class="mnm-line">
                        <div class="mnm-line-title"><?php _e("Message *", "s1b"); ?></div>
                        <textarea class="input-item mnm-body" name="message"><?php echo $this->message; ?></textarea>
                    </div>
                    <div class="buttons-bar">
                        <div class="inner-padding">
                            <?php _e("Champs obligatoires *", ""); ?>
                            <button
                                class="button bt-blue-m float-right margin-left"><?php _e("Envoyer", "s1b"); ?></button>
                            <a class="button bt-black-xs float-right" href="javascript:history.back()"
                               class="link"><?php _e("Annuler", "s1b") ?></a>
                        </div>
                    </div>
                </div>
            </form>
        <?php } ?>
    </div>
</div>
<div id="content-right">
    <div class="right-frame">
        <?php
        $ad = new Ad("", "");
        echo $ad->get();
        ?>
    </div>
</div>