<div class="user-event">
    <div class="inner-padding-10">
        <div class="ue-friendimage">        
            <a href="<?php echo $friendProfileLink;?>"><img border="0" class="image-frame image-thumb-square-small" src="<?php echo $userFriendImg;?>" /></a>
        </div>
        <div class="ue-description">
            <div class="ue-resume">
                <?php echo $resume;?>
            </div>
            <?php if ($userBookRelated) {?>
            <div class="ue-book">
                <div class="ue-bookimage">                
                    <a class="link" href="<?php echo $bookLink;?>"><img border="0" class="image-thumb-small image-frame" src="<?php echo $bookImageUrl;?>"></a>                
                </div>
                <div class="ue-bookdescription">
                    <div class="ue-booktitle">
                        <?php echo $bookTitle;?>
                    </div>
                    <?php echo sprintf(__("de %s","s1b"), $bookAuthor);?>
                    <div class="ue-booklink">
                        <a class="link" href="<?php echo $bookLink;?>"><?php _e("Voir ce livre","s1b");?></a>
                    </div>
                </div>
            </div>
            <?php } ?>
            <?php if ($additionalContent) {?>
            <div class="ue-additional">
                <?php echo $additionalContent;?>
            </div>
            <?php } ?>
            <div class="ue-date">
                <?php echo $creationDate;?>
            </div>
        </div>
    </div>
</div>
<?php if ($addSep) {?>
<div class="horizontal-sep-1"></div>
<?php }?>