<div class="user-event">
    <div class="ue-friendimage">        
        <img class="image-frame image-thumb-square-small" src="<?php echo $userFriendImg;?>" />
    </div>
    <div class="ue-description">
        <div class="ue-resume">
            <?php echo $resume;?>
        </div>
        <div class="ue-book">
            <div class="ue-bookimage">                
                <img class="image-thumb-small image-frame" src="<?php echo $bookImageUrl;?>">
            </div>
            <div class="ue-bookdescription">
                <div class="ue-booktitle">
                    <?php echo $bookTitle;?>
                </div>
                <div class="ue-booklink">
                    <a class="link" href="<?php echo $bookLink;?>"><?php _e("Voir ce livre","s1b");?></a>
                </div>
            </div>
        </div>
        <?php if ($additionalContent) {?>
        <div class="ue-additional">
            <?php echo $additionalContent;?>
        </div>
        <?php } ?>
        <div class="ue-date">
            <?php echo $creationDate;?>
        </div>
    </div>
</div>
<?php if ($addSep) {?>
<div class="horizontal-sep-1"></div>
<?php }?>