<?php
use Sb\View\Components\Ad;
use Sb\View\UserProfile;
use Sb\Entity\Urls;
use Sb\Helpers\HTTPHelper;

?>

<div class="user-profile-bkg">
    <div id="content-center">
        <?php
        $profileView = new UserProfile($this->user, $this->userSettings, false, false, false);
        echo $profileView->get();
        ?>
        <div class="horizontal-sep-1"></div>
        <div class="profile-edit-form">
            <form action="<?php echo HTTPHelper::Link(Urls::USER_PROFILE_SUBMIT_PASSWORD)?>" method="post">
                <table>
                    <tr>
                        <td class="pef-label">
                            <?php _e("Ancien mot de passe", "s1b"); ?>
                        </td>
                        <td>
                            <input type="Password" class="input-item textinput" name="Password_old" id="Password_old"
                                   value=""/>
                        </td>
                    </tr>
                    <tr>
                        <td class="pef-label">
                            <?php _e("Nouveau mot de passe", "s1b"); ?>
                        </td>
                        <td>
                            <input type="Password" class="input-item textinput" name="Password_modif"
                                   id="Password_modif" value=""/>
                        </td>
                    </tr>
                </table>
                <div class="buttons-bar">
                    <div class="inner-padding">
                        <button
                            class="float-right button bt-blue-m margin-right margin-left"><?php _e("Valider", "s1b"); ?></button>
                        <?php if (!$_POST) { ?>
                            <a class="button bt-black-xs float-right" href="javascript:history.back()"
                               class="link"><?php _e("Annuler", "s1b") ?></a>
                        <?php } ?>
                    </div>
                </div>
            </form>
        </div>
    </div>
    <div id="content-right">
        <div class="right-frame">
            <?php
            $ad = new Ad("", "");
            echo $ad->get();
            ?>
        </div>
    </div>
</div>