<div class="user-profile-bkg">
    <div id="content-center">
        <?php echo $this->profileView;?>
        <div class="horizontal-sep-1"></div>
        <div class="profile-edit-form">
            <form action="<?php echo $this->submitUrl; ?>" method="post">                            
                <table>
                    <tr>
                        <td class="pef-label">
                            <?php _e("Nom", "s1b"); ?>
                        </td>
                        <td>
                            <input type="text" class="input-item textinput" name="LastName_modif" id="LastName_modif" value="<?php echo $this->user->getLastName(); ?>" />
                        </td>
                    </tr>
                    <tr>
                        <td class="pef-label">
                            <?php _e("Prénom", "s1b"); ?>
                        </td>
                        <td>
                            <input type="text" class="input-item textinput" name="FirstName_modif" id="FirstName_modif" value="<?php echo $this->user->getFirstName(); ?>" />
                        </td>
                    </tr>
                    <tr>
                        <td class="pef-label">
                            <?php _e("Identifiant", "s1b"); ?>
                        </td>
                        <td>
                            <input type="text" class="input-item textinput" name="UserName_modif" id="UserName_modif" value="<?php echo $this->user->getUserName(); ?>" />
                        </td>
                    </tr>
                    <tr>
                        <td class="pef-label">
                            <?php _e("Anniversaire (jj/mm/aaaa)", "s1b"); ?>
                        </td>
                        <td>
                            <input type="text" class="input-item textinput birthDateField" name="BirthDay_pre_modif" id="BirthDay_pre_modif" value="<?php echo (!$this->user->getBirthDay() ? 'dd/mm/yyyy' : $this->user->getBirthDay()->format('d/m/Y')); ?>" />
                        </td>
                    </tr>
                    <tr>
                        <td class="pef-label">
                            <?php _e("Adresse", "s1b"); ?>
                        </td>
                        <td>
                            <input type="text" class="input-item textinput" name="Address_modif" id="Address_modif" value="<?php echo $this->user->getAddress(); ?>" />
                        </td>
                    </tr>
                    <tr>
                        <td class="pef-label">
                            <?php _e("Ville", "s1b"); ?>
                        </td>
                        <td>
                            <input type="text" class="input-item textinput" name="City_modif" id="City_modif" value="<?php echo $this->user->getCity(); ?>" />
                        </td>
                    </tr>
                    <tr>
                        <td class="pef-label">
                            <?php _e("Code postal", "s1b"); ?>
                        </td>
                        <td>
                            <input type="text" class="input-item textinput" name="ZipCode_modif" id="ZipCode_modif" value="<?php echo ($this->user->getZipCode() == "0" ? "" : $this->user->getZipCode()); ?>" />
                        </td>
                    </tr>
                    <tr>
                        <td class="pef-label">
                            <?php _e("Pays", "s1b"); ?>
                        </td>
                        <td>
                            <select class="input-item selectinput" name="Country_modif">
                                <option></option>
                                <?php foreach ($this->countries as $country) { ?>
                                    <option <?php echo (($this->userCountry && $this->userCountry->getIso3166() == $country->getIso3166()) ? "selected" : "");?> value="<?php echo $country->getIso3166(); ?>">
                                        <?php echo ($this->userLang == "fr_FR" ? $country->getLabel_french(): $country->getLabel_english()); ?>
                                    </option>
                                <?php } ?>
                            </select>
                        </td>
                    </tr>
                    <tr>
                        <td class="pef-label">
                            <?php _e("Langue", "s1b"); ?>
                        </td>
                        <td>
                            <select class="input-item selectinput" name="Language_modif">
                                <option value="<?php _e("français", "s1b"); ?>" <?php echo ( $this->userLang == "fr_FR"  ? "selected" : ""); ?>><?php _e("français", "s1b"); ?></option>
                                <option value="<?php _e("anglais", "s1b"); ?>" <?php echo ( $this->userLang != "fr_FR" ? "selected" : ""); ?>><?php _e("anglais", "s1b"); ?></option>
                            </select>                            
                        </td>
                    </tr>
                    <tr>
                        <td class="pef-label">
                            <?php _e("Sexe", "s1b"); ?>
                        </td>
                        <td>
                           <input <?php echo ($this->user->getGender() == "male" ? "checked" : ""); ?> type="radio" name="Gender_modif" id="radio" value="male" /><label for="radio1"><?php _e("masculin", "s1b"); ?></label>
                           <br/>                                    
                           <input <?php echo ($this->user->getGender() == "female" ? "checked" : ""); ?> type="radio" name="Gender_modif" id="radio" value="female" /><label for="radio1"><?php _e("féminin", "s1b"); ?></label>
                        </td>
                    </tr>
                </table>

                <?php _e("* champs obligatoires", "s1b"); ?>
                
                <div class="buttons-bar">
                    <div class="inner-padding">
                        <button class="float-right button bt-blue-m margin-right margin-left"><?php _e("Valider","s1b");?></button>
                        <?php if (!$_POST) {?>
                        <a class="button bt-black-xs float-right" href="javascript:history.back()" class="link"><?php _e("Annuler", "s1b") ?></a>
                        <?php } ?>
                    </div>
                </div>
            </form>
        </div>            
    </div>
    <div id="content-right">
        <div class="right-frame">
            <?php
            $ad = new \Sb\View\Components\Ad("","");
            echo $ad->get();
            ?>
        </div>
    </div>
</div>
