<div class="login-form">
    <form name="Connexion_S1B" action="<?php echo \Sb\Helpers\HTTPHelper::Link(""); ?>" method="POST">
        <input type="hidden" name="connexion_type" value="S1B" />
        <div class="lf-label">Connexion</div>
        <div class="lf-fields">
            <input class="input loginField" type="text" name="email" value="Email"/>
            <input class="input loginPwd" type="password" name="password" value="Mot de passe" />
            <input class="loginDef" type="hidden" value="Email"/>
        </div>
        <div class="lf-button">
            <button class="lfb-submit bt-blue-m button">S'identifier</button>
            <a class="lfb-lostpassword" href="<?php echo \Sb\Helpers\HTTPHelper::Link(\Sb\Entity\Urls::LOST_PASSWORD); ?>" >Mot de passe perdu</a>
        </div>
        <div class="lf-fbconnect">
            <a class="button bt-facebook-s" href="<?php echo \Sb\Helpers\HTTPHelper::Link(\Sb\Entity\Urls::LOGIN_FACEBOOK); ?>">connect</a>
        </div>
    </form>
</div>


