<div class="search-form <?php echo ($isConnected? "connected" : "");?>" >
    <form name="searchForm" method="post" action="<?php echo $formAction;?>">
        <input type="hidden" name="mode" value="SUBMIT" />
        <input type="hidden" name="pagenumber" value="1" />
        <div class="sf-label">
            <?php if ($isConnected) {
                echo("Rechercher un titre, un auteur, ISBN");
            }else {
                echo("Rechercher");
            }?>
        </div>
        <div class="sf-field search-field">
            <div class="sff-input search-field-input">
                <input class="searchTerm bookSearchTermField" type="text" name="searchTerm" value="<?php echo ($showSearchTermDef ? $searchTerm : "");?>" />
                <input type="hidden" class="bookSearchTermDef" value="<?php echo $searchTermDef;?>" />
            </div>
            <button class="sff-button search-button">&nbsp;</button>
        </div>
    </form>
</div>
