<?php
use Sb\Helpers\HTTPHelper,
    Sb\Helpers\StringHelper,

    Sb\Entity\Urls,
    Sb\Entity\Constants,

    Sb\Db\Service\BookSvc,

    Sb\Flash\Flash,

    Sb\View\Components\SearchForm,
    Sb\View\Components\LoginForm,
    Sb\View\Components\UserNavigation;


$globalConfig = new Sb\Config\Model\Config();
$globalContext = new \Sb\Context\Model\Context();
?>
<!DOCTYPE html>
<!-- layout.html booo-->
<html xmlns:fb="http://ogp.me/ns/fb#">
<head>
    <title><?php echo $this->tagTitle; ?></title>

    <?php if ($this->urlCanonical) : ?>
    <link rel="canonical" href="<?php echo $this->urlCanonical; ?>"/>
    <?php endif; ?>

    <meta name="description" content="<?php echo $this->metaDescription; ?>"/>
    <meta name="keywords" content="<?php echo $this->metaKeywords; ?>"/>
    <?php if ($this->pageImage) : ?>
    <meta property="og:image" content="<?php echo $this->pageImage; ?>"/>
    <?php endif; ?>

    <link type="text/css" media="screen" rel="stylesheet" href="<?php echo $globalContext->getBaseUrl(); ?>Resources/css/bootstrap.min.css"/>
    <link type="text/css" media="screen" rel="stylesheet" href="<?php echo $globalContext->getBaseUrl(); ?>Resources/css/share1book<?php echo($globalConfig->getIsProduction() ? "-min" : ""); ?>.css?v=<?php echo VERSION; ?>"/>
    <link type="text/css" media="screen" rel="stylesheet" href="<?php echo $globalContext->getBaseUrl(); ?>Resources/js/jquery/overcast/jquery-ui-1.8.18.custom.css"/>

    <?php if ($globalConfig->getIsProduction()) : ?>
    <!-- PRODUCTION -->
    <?php endif; ?>

    <link rel="icon" type="image/png" href="<?php echo $globalContext->getBaseUrl() . "Resources/images/favicons/favicon.ico"; ?>"/>

    <link rel="shortcut icon" type="image/x-icon" href="<?php echo $globalContext->getBaseUrl(); ?>Resources/images/favicons/favicon.ico"/>

    <script type="text/javascript" src="<?php echo $globalContext->getBaseUrl(); ?>Resources/js/jquery/jquery-1.11.3.min.js"></script>
    <script type="text/javascript" src="<?php echo $globalContext->getBaseUrl(); ?>Resources/js/bootstrap/bootstrap.min.js"></script>

    <meta charset="UTF-8"/>
    <meta name="language" content="fr-FR"/>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
    <!--HTML4-->
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <!--XHTML 1.1-->
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta http-equiv="X-UA-Compatible" content="IE=EmulateIE7"/>
    <meta http-equiv="content-language" content="ll-cc">
    <meta name="verification" content="90976ef46595e2d7ff7ce4419ff6dc05"/>
    <meta name="msvalidate.01" content="E62B545AC4DE99DA99D381175475444F"/>
    <meta name="norton-safeweb-site-verification" content="jh6la0lgxqne8t-qrkb1vtxf9tqfdhqepiff6e6qkbcv6951uvuam70bh7fp2e371h08q687xlh7v1641xjypiwmqs03aaii5sh9gwbns3hptuzhdp2mk5d-hkj4jwz7"/>
    <?php echo $this->headLink(); ?>



</head>
<body>

<div id="loading">
    <div id="loadingMsg"><?php _e("Chargement en cours...", "s1b"); ?></div>
</div>

<!-- Debut div page -->
<div id="page">
    <!-- Debut div header -->
    <div id="header">
        <div id="header-top">
            <div class="header-inner">
                <a href="<?php echo HTTPHelper::Link(""); ?>">
                    <img border="0" src="<?php echo $globalContext->getBaseUrl(); ?>Resources/images/logo.png"
                         alt="logo Cherbouquin"/>
                </a>
            </div>
        </div>
        <div id="header-bottom">
            <div class="header-inner">
                <div id="nav-main">
                    <?php
                    $searchForm = new SearchForm;
                    echo $searchForm->get();

                    if (!$globalContext->getConnectedUser()) {
                        $loginForm = new LoginForm;
                        echo $loginForm->get();
                    }
                    ?>
                </div>
            </div>
        </div>
    </div>
    <!-- Debut div content -->
    <div id="content">
        <?php
        if ($globalContext->getConnectedUser()) {
            $userNavigation = new UserNavigation;
            echo $userNavigation->get();
        }
        ?>
        <!-- Debut div content-wrap -->
        <div id="content-wrap" class="col-xs-12">

            <?php echo $this->layout()->content; ?>

            <!-- Début div footer-wrap -->
            <div id="footer-wrap">
                <div id="footer-top">

                    <div class="ft-item">
                        <div class="inner-padding-12">
                            <h2 class="ft-item-title">
                                <a class="link"
                                   href="<?php echo HTTPHelper::Link(Urls::TOPS_BOOKS); ?>"><?php _e("<strong>Top</strong> des livres", "s1b"); ?></a>
                            </h2>

                            <div class="ft-item-content">
                                <?php
                                $topsBooks = BookSvc::getInstance()->getTopsFooter();
                                echo "<ul>";
                                foreach ($topsBooks as $topsBook) {
                                    echo "<li><h3><a title=\"" . $topsBook->getTitle() . " - " . $topsBook->getOrderableContributors() . "\" href=\"" . HTTPHelper::Link($topsBook->getLink()) . "\">"
                                        . \Sb\Helpers\StringHelper::tronque($topsBook->getTitle(), 40)
                                        . "</a></h3></li>";
                                }
                                echo "</ul>";
                                ?>
                            </div>
                        </div>
                    </div>
                    <div class="ft-item">
                        <div class="inner-padding-12">
                            <h2 class="ft-item-title">
                                <a class="link"
                                   href="<?php echo HTTPHelper::Link(Urls::BLOW_OF_HEARTS_BOOKS); ?>"><strong><?php _e("Coups de coeur", "s1b"); ?></strong></a>
                            </h2>

                            <div class="ft-item-content">
                                <?php
                                $bohs = BookSvc::getInstance()->getBOHForFooter();
                                echo "<ul>";
                                foreach ($bohs as $boh) {
                                    echo "<li><h3><a title=\"" . $boh->getTitle() . " - " . $boh->getOrderableContributors() . "\" href=\"" . HTTPHelper::Link($boh->getLink()) . "\">"
                                        . StringHelper::tronque($boh->getTitle(), 40)
                                        . "</a></h3></li>";
                                }
                                echo "</ul>";
                                ?>
                            </div>
                        </div>
                    </div>
                    <div class="ft-item">
                        <div class="inner-padding-12">
                            <h2 class="ft-item-title">
                                <a class="link"
                                   href="<?php echo HTTPHelper::Link(Urls::LAST_ADDED_BOOKS); ?>"><strong><?php _e("Derniers livres ajoutés", "s1b"); ?></strong></a>
                            </h2>

                            <div class="ft-item-content">
                                <?php
                                $lastlyAddedBooks = BookSvc::getInstance()->getLastlyAddedForFooter();
                                echo "<ul>";
                                foreach ($lastlyAddedBooks as $lastlyAddedBook) {
                                    echo "<li><h3><a title=\"" . $lastlyAddedBook->getTitle() . " - " . $lastlyAddedBook->getOrderableContributors() . "\" href=\"" . HTTPHelper::Link($lastlyAddedBook->getLink()) . "\">"
                                        . StringHelper::tronque($lastlyAddedBook->getTitle(), 40)
                                        . "</a></h3></li>";
                                }
                                echo "</ul>";
                                ?>
                            </div>
                        </div>
                    </div>
                    <div class="ft-item last">
                        <div class="inner-padding-12">
                            <h2 class="ft-item-title"><?php echo sprintf(__("<strong>%s</strong> sur les réseaux", "s1b"), Constants::SITENAME); ?></h2>

                            <div class="ft-item-content">
                                <a target="_blank"
                                   href="http://www.facebook.com/CherBouquin"
                                   class="picto-facebook-m"
                                   title="<?php echo sprintf(__("%s sur Facebook", "s1b"), Constants::SITENAME); ?>"></a>
                            </div>
                            <div class="ft-item-content">
                                <a target="_blank"
                                   href="https://twitter.com/#!/cherbouquin"
                                   class="ft-twitter"
                                   title="<?php echo sprintf(__("%s sur Twitter", "s1b"), Constants::SITENAME); ?>"></a>
                            </div>
                            <div class="ft-item-content">
                                <a target="_blank" href="http://pinterest.com/cherbouquin"
                                   class="ft-pinterest"
                                   title="<?php echo sprintf(__("%s sur Pinterest", "s1b"), Constants::SITENAME); ?>"></a>
                            </div>
                            <div class="ft-item-content">
                                <a target="_blank"
                                   href="https://plus.google.com/u/0/b/106650239259479003219/106650239259479003219/posts"
                                   class="ft-googleplus"
                                   title="<?php echo sprintf(__("%s sur Google+", "s1b"), Constants::SITENAME); ?>"></a>
                            </div>
                        </div>
                    </div>
                </div>
                <div id="footer-bottom">
                    <div class="inner-padding">
                        <div class="fb-left float-left">&copy;
                        	<?php $date = new Zend_Date(); echo $date->toString('yyyy');?> <?php echo Constants::SITENAME; ?></div>
                        <div class="fb-right float-right">
                            <ul>
                                <li>
                                    <a class="link"
                                       href="<?php echo HTTPHelper::Link(Urls::ABOUT); ?>"><?php _e("A propos", "s1b"); ?></a><br/>
                                    <a class="link"
                                       href="<?php echo HTTPHelper::Link(Urls::TEAM); ?>"><?php _e("L'équipe", "s1b"); ?></a><br/>
                                    <a class="link"
                                       href="<?php echo HTTPHelper::Link(Urls::PARTNERS); ?>"><?php _e("Nos partenaires", "s1b"); ?></a><br/>
                                    <a class="link"
                                       href="<?php echo HTTPHelper::Link(Urls::CONTACT); ?>"><?php _e("Contact", "s1b"); ?></a>
                                </li>
                                <li>
                                    <a class="link"
                                       href="<?php echo HTTPHelper::Link(Urls::PRESS); ?>"><?php _e("Presse", "s1b"); ?></a><br/>
                                    <a class="link"
                                       href="<?php echo HTTPHelper::Link(Urls::NEWSLETTERS); ?>"><?php _e("Newsletters", "s1b"); ?></a><br/>
                                    <a class="link"
                                       href="<?php echo HTTPHelper::Link(Urls::PRESS_REVIEW); ?>"><?php _e("Revues de presse", "s1b"); ?></a>
                                </li>
                                <li>
                                    <a class="link"
                                       href="<?php echo HTTPHelper::Link(Urls::HOW_TO); ?>"><?php _e("Comment ça marche?", "s1b"); ?></a><br/>
                                    <a class="link"
                                       href="<?php echo HTTPHelper::Link(Urls::STEP_BY_STEP); ?>"><?php _e("Pas à pas", "s1b"); ?></a>
                                </li>
                                <li>
                                    <a class="link"
                                       href="<?php echo HTTPHelper::Link(Urls::HELP_US); ?>"><?php _e("Nous aider", "s1b"); ?></a>
                                </li>
                                <li>
                                    <a class="link" target="_blank"
                                       href="<?php echo HTTPHelper::Link("CGU/CGU-26-09-2012.pdf"); ?>"><?php _e("Conditions générales d'utilisations", "s1b"); ?></a>
                                </li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
            <!-- Fin div footer-wrap -->
        </div>
        <!-- Fin div content-wrap -->
        <?php Flash::showFlashes(); ?>
    </div>
    <!-- Fin div content -->
</div>


<?php
$facebookJs = 'http://connect.facebook.net/fr_FR/all.js#xfbml=1&appId=' . $globalConfig->getFacebookApiId();
$facebookInviteText = __("Rejoignez vos amis, suivez les livres que vous leurs prêtez et partagez avec eux vos dernières lectures et envies", "s1b");
$ajaxUrl = str_replace("index.php", "", str_replace("public/index.php", "", $_SERVER['SCRIPT_NAME']));
?>
<script type='text/javascript'>
    var share1BookAjax = {
        "url": "<?php echo $ajaxUrl; ?>",
        "facebookJs": "<?php echo $facebookJs; ?>",
        "facebookInviteText": "<?php echo $facebookInviteText; ?>"
    };
</script>

<script type="text/javascript"
        src="<?php echo $globalContext->getBaseUrl(); ?>Resources/js/jquery/jquery-ui-1.8.18.custom.min.js"></script>
<script type="text/javascript"
        src="<?php echo $globalContext->getBaseUrl(); ?>Resources/js/jquery/jquery.ui.datepicker-fr.js"></script>

<script type="text/javascript" src="<?php echo $globalContext->getBaseUrl(); ?>Resources/js/ajax.js"></script>
<script type="text/javascript" src="<?php echo $globalContext->getBaseUrl(); ?>Resources/js/book.js?v=1"></script>
<script type="text/javascript" src="<?php echo $globalContext->getBaseUrl(); ?>Resources/js/library.js"></script>
<script type="text/javascript"
        src="<?php echo $globalContext->getBaseUrl(); ?>Resources/js/pushedBooks.js"></script>
<script type="text/javascript"
        src="<?php echo $globalContext->getBaseUrl(); ?>Resources/js/searchResult.js"></script>

<script type="text/javascript" src="<?php echo $globalContext->getBaseUrl(); ?>Resources/js/facebook.js"></script>


<?php if ($globalConfig->getIsProduction()) { ?>
    <script type="text/javascript">
        var _gaq = _gaq || [];
        _gaq.push(['_setAccount', 'UA-34691855-1']);
        _gaq.push(['_trackPageview']);
        _gaq.push(['_trackPageLoadTime']);
        (function () {
            var ga = document.createElement('script');
            ga.type = 'text/javascript';
            ga.async = true;
            ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
            var s = document.getElementsByTagName('script')[0];
            s.parentNode.insertBefore(ga, s);
        })();
    </script>
<?php } ?>

<?php echo $this->placeholder('footer') ?>
</body>
</html>