

<!--
.bt-delete {background: url("../images/sprite-buttons.png") no-repeat scroll 0 -390px transparent;float: left;height: 30px;padding: 0;width: 30px;}
.bb-btadd {background: url("../images/sprite-buttons.png") no-repeat scroll 0 -33px transparent;display: block;float: right;font-size: 0.7em;height: 29px;text-align: center;width: 66px;}
.bb-btvalidate {background: url("../images/sprite-buttons.png") no-repeat scroll 0 -33px transparent;display: block;float: right;font-size: 0.7em;height: 29px;text-align: center;width: 66px;}
.lfb-submit {background: url("../images/sprite-buttons.png") no-repeat scroll 0 -143px transparent;float: left; padding: 0; width: 90px; height: 30px;}
.lf-fbconnect {background: url("../images/sprite-buttons.png") no-repeat scroll 0 -241px transparent;float: left;height: 22px;padding: 10px 0 0;width: 78px;}
.bv-lend {margin-top: 70px; margin-right: 5px; background: url("../images/sprite-buttons.png") no-repeat scroll 0 0 transparent;float: left; padding: 6px 0;width: 102px;}
.bv-edit {margin-top: 68px; margin-right: 5px; background: url("../images/sprite-buttons.png") no-repeat scroll 0 -143px transparent;float: left; padding: 8px 0;;width: 90px}
.ci-button {background: url("../images/sprite-buttons.png") no-repeat scroll 0 -274px transparent;font-size: 1.5em;height: 26px;margin-left: 65px;margin-top: 9px;padding: 9px 0;width: 139px;}
.utc-button {background: url("../images/sprite-buttons.png") no-repeat scroll 0 -211px transparent;padding: 7px 0;width: 128px;}
.utc-button A, .utc-button A:visited, .utc-button A:hover {color:#FFF; text-decoration: none;}
.bs-button {background: url("../images/sprite-buttons.png") no-repeat scroll 0 -143px transparent;border: medium none;color: #FFFFFF;float: left;font-weight: bold;height: 30px;padding: 0;width: 90px;     font-size: 1em; cursor:pointer;}
.bv-share {background: url("../images/sprite-buttons.png") no-repeat scroll 0 -444px transparent;float: right;height: 39px;padding: 43px 6px 11px 5px; width: 84px;}
.bv-sharefacebook {margin-top: 68px; margin-right: 5px; background: url("../images/sprite-buttons.png") no-repeat scroll 0 -143px transparent;float: left; height: 22px; padding: 10px 0 0 5px;width: 83px;}
.bv-requestborrow {background: url("../images/sprite-buttons.png") no-repeat scroll 0 0 transparent; float: left; line-height: 18px; margin-right: 5px; margin-top: 70px; padding: 6px 0; width: 103px;}
-->

<div>
    <a href="" class="button bt-delete" >test de bouton</a>
</div>
<br/><br/><br/><br/><br/><br/><br/><br/><br/><br/>
<div>
    <a href="" class="button bt-blue-big">test de bouton</a>
</div>
<br/><br/><br/><br/><br/><br/><br/><br/><br/><br/>
<div>
    <a href="" class="button bb-btadd">test de bouton</a>
</div>
<br/><br/><br/><br/><br/><br/><br/><br/><br/><br/>
<div>
    <a href="" class="button bt-blue-small">bt-blue-small</a>
</div>
<br/><br/><br/><br/><br/><br/><br/><br/><br/><br/>
<div>
    <a href="" class="button bb-btvalidate">test de bouton</a>
</div>
<br/><br/><br/><br/><br/><br/><br/><br/><br/><br/>
<div>
    <a href="" class="button lf-fbconnect">test de bouton</a>
</div>
<br/><br/><br/><br/><br/><br/><br/><br/><br/><br/>
<div>
    <div>
        <a href="" class="button bt-black-s">bt-black-s</a>
    </div>
    <div>
        <a href="" class="button bt-black-m">bt-black-m</a>
    </div>
    <div>
        <a href="" class="button bt-black-l">bt-black-l</a>
    </div>
</div>
<br/><br/><br/><br/><br/><br/><br/><br/><br/><br/>
<div>
    <div>
        <a href="" class="button bt-blue-xs">bt-blue-xs</a>
    </div>
    <div>
        <a href="" class="button bt-blue-s">bt-blue-s</a>
    </div>
    <div>
        <a href="" class="button bt-blue-m">bt-blue-m</a>
    </div>
    <div>
        <a href="" class="button bt-blue-l">bt-blue-l</a>
    </div>
    <div>
        <a href="" class="button bt-blue-xl">bt-blue-xl</a>
    </div>
</div>


<div>
    <a href="" class="button nul-button">test de bouton</a>
</div>