<div class="pb-item pushedBook">
    <div class="pbi-image">
        <a title="<?php echo $bookTitle; ?> - <?php echo $bookAuthors; ?>" href="<?php echo $viewBookLink; ?>"><?php echo $image; ?></a>
    </div>
    <div class="pbi-content">
        <h2 class="pbi-title">
            <?php echo $bookTitle; ?>
        </h2>
        <div class="pbi-description">
            <?php echo $bookDescription; ?>
        </div>
        <div class="pbi-publication">
            <?php echo $bookPublication; ?>
        </div>
        <div class="pbi-authors">
            <?php echo $bookAuthors; ?>
        </div>
        <a class="book-link" href="<?php echo $viewBookLink; ?>"><?php echo "Découvrir ce livre"; ?> </a>
        <div class="pbi-giftoption">
            <div class="pbi-giftoption-addoption">
                <?php if (!$isOffered) { ?>
                    <span class="pbi-giftoption-notbought"><?php _e("Ce livre n'a pas encore été offert.","s1b");?></span>
                    <a href="<?php echo $setAsOfferedLink;?>" class="button bt-blue-xxxl"><?php _e("Marquez-le comme acheté", "s1b"); ?></a>
                <?php } else { ?>
                    <?php 
                    global $context;
                    $giftOptionFromMe = ($offerer->getId() == $context->getConnectedUser()->getId());
                    ?>
                    <span class="pbi-giftoption-bought">
                        <?php 
                        if ($giftOptionFromMe)
                            _e("Ce livre a déjà été acheté par moi.", "s1b");
                        else 
                            _e("Ce livre a déjà été acheté.", "s1b");
                        ?>
                    </span>
                    <?php if ($giftOptionFromMe)
                        echo sprintf(__("Je souhaite l'<a class=\"link\" href=\"%s\">annuler</a>.", "s1b"), $deactivateGiftOptionLink);
                    ?>
                <?php } ?>            
            </div>
            <div class="pbi-giftoption-buy">
                <a class="button bt-amazon float-left margin-right" target="_blank" href="<?php echo $buyOnAmazonLink; ?>" title="<?php _e("Acheter sur Amazon", "s1b");?>"></a>
                <?php if ($buyOnFnacLink) { ?>
                <a class="button bt-fnac float-left" target="_blank" href="<?php echo $buyOnFnacLink; ?>" title="<?php _e("Acheter sur Fnac.com", "s1b");?>"></a>
                <?php } ?>
            </div>
        </div>
    </div>
</div>