<?php
use Sb\View\Components\Ad;
use Sb\Helpers\HTTPHelper;
use Sb\Helpers\StringHelper;
use Sb\Helpers\UserHelper;
use Sb\Entity\Urls;
use Sb\Entity\UserDataVisibility;
use Sb\Helpers\ArrayHelper;

global $globalContext;
?>

<div class="wishlist-list">
    <div id="content-wide">
        <div class="fl-search">
            <div class="inner-padding">
                <div class="fls-label"><?php _e("Rechercher une liste d'envie", "s1b"); ?></div>
                <div class="fls-form">
                    <?php echo $this->form;?>
                </div>
            </div>
        </div>
    </div>
    <div id="content-center">
        <?php
        $i = 0;
        foreach ($this->users as $friend) {
            $friendWishListLink = HTTPHelper::Link(Urls::USER_FRIENDS_WISHLIST, array(
                    "friendId" => $friend->getId()
            ));
            if (($i % 3 == 0) && ($i != 0)) {
                echo "<div class=\"horizontal-sep-1\"></div>";
            }
            $i += 1;
            ?>                        
            <div class="friend-item">
            <div class="inner-padding">
                <img class="image-frame image-thumb-square" src="<?php echo $friend->getGravatar();?>" />
                <div class="fi-line">
                    <span class="fil-value fil-username">
                            <?php echo StringHelper::tronque(UserHelper::getFullName($friend), 25);?>                            
                        </span>
                </div>
                <div class="fi-line">
                    <span class="fil-label"><?php _e("Email : ","s1b");?></span> <span class="fil-value"><?php echo (($friend->getSetting()->getDisplayEmail() != UserDataVisibility::NO_ONE)? StringHelper::tronque($friend->getEmail(), 30) : __("donnée privée", "s1b"));?></span>
                </div>                
                <div class="fi-line">
                    <span class="fil-label"><?php _e("Identifiant : ","s1b");?></span> <span class="fil-value"><?php echo $friend->getUserName();?></span>
                </div>                                
                <div class="fi-line">
                    <a href="<?php echo $friendWishListLink; ?>" class="link"><?php echo __("Voir sa liste d'envie", "s1b"); ?></a>
                </div>
            </div>
        </div>
            <?php }?>      
        
    </div>
    <div id="content-right">
        <div class="right-frame">
        <?php
        $ad = new Ad("user_friends", "2432422854");
        echo $ad->get();
        ?>
        </div>
    </div>
</div>