<p><?php _e("Un ami vient de créér un compte sur share1book.com pour vous.", "s1b"); ?></p>
<p><?php _e("Vous pouvez accéder à votre compte en cliquant sur le lien ci-dessous.", "s1b"); ?></p>
<p>Votre login : [@login]</p>
<p>Votre mot de passe : [@password]</p>
<p><a href="[@url]"><?php _e("Connectez vous", "s1b"); ?></a></p>
<p><?php _e("Il a indiqué vous avoir emprunté un livre : ", "s1b"); ?></p>
<p><?php _e("Titre : [@title]", "s1b"); ?></p>
<p><?php _e("Le prêt est pour le moment en attente de validation de votre part. Auparavant, vous devez valider votre compte et accèpter la demande d'ajout à la liste d'ami de votre ami.","share1book"); ?></p>