<?php

namespace Proxies\__CG__\Sb\Db\Model;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class Invitation extends \Sb\Db\Model\Invitation implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    /** @private */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int) $this->_identifier["id"];
        }
        $this->__load();
        return parent::getId();
    }

    public function setId($id)
    {
        $this->__load();
        return parent::setId($id);
    }

    public function getCreation_date()
    {
        $this->__load();
        return parent::getCreation_date();
    }

    public function setCreation_date($creation_date)
    {
        $this->__load();
        return parent::setCreation_date($creation_date);
    }

    public function getLast_modification_date()
    {
        $this->__load();
        return parent::getLast_modification_date();
    }

    public function setLast_modification_date($last_modification_date)
    {
        $this->__load();
        return parent::setLast_modification_date($last_modification_date);
    }

    public function getSender()
    {
        $this->__load();
        return parent::getSender();
    }

    public function setSender($sender)
    {
        $this->__load();
        return parent::setSender($sender);
    }

    public function getGuest()
    {
        $this->__load();
        return parent::getGuest();
    }

    public function setGuest($guest)
    {
        $this->__load();
        return parent::setGuest($guest);
    }

    public function getIs_accepted()
    {
        $this->__load();
        return parent::getIs_accepted();
    }

    public function setIs_accepted($is_accepted)
    {
        $this->__load();
        return parent::setIs_accepted($is_accepted);
    }

    public function getIs_validated()
    {
        $this->__load();
        return parent::getIs_validated();
    }

    public function setIs_validated($is_validated)
    {
        $this->__load();
        return parent::setIs_validated($is_validated);
    }

    public function getToken()
    {
        $this->__load();
        return parent::getToken();
    }

    public function setToken($token)
    {
        $this->__load();
        return parent::setToken($token);
    }

    public function IsValid()
    {
        $this->__load();
        return parent::IsValid();
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'id', 'creation_date', 'last_modification_date', 'is_accepted', 'is_validated', 'token', 'sender', 'guest');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields as $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}