<div id="content-center">

    <div id="chronicle-detail">
        <?php echo $this->chronicle; ?>
        <?php echo $this->otherChoniclesSameType; ?>
        <?php echo $this->reviews; ?>
    </div>
    
</div>

<div id="content-right">
    
    <div class="right-frame">
        <?php echo $this->newsReader; ?>
    </div>
    
    <div class="right-frame">
        <?php echo $this->ad; ?>
    </div>
    
    <div class="right-frame">
        <?php echo $this->pressReviewsSubscriptionWidget; ?>
    </div>
    
    <div class="right-frame">
        <?php echo $this->authorChroniclesView; ?>
    </div>
    
</div>
