<div id="chronicle-detail">
    <div id="content-center">
        <?php echo $this->chronicle; ?>
        <?php echo $this->otherChoniclesSameType; ?>
        <?php echo $this->reviews; ?>
    </div>
    <div id="content-right">
        <div class="right-frame">
            <?php echo $this->authorChroniclesView; ?>
        </div>
        <div class="right-frame">
            <?php echo $this->ad; ?>
        </div>
    </div>
</div>